spring:
  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
    format:
      date: iso
      date-time: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    root: INFO
    org:
      hibernate: INFO

server:
  port: 8081